global:
  scrape_interval: 30s
  evaluation_interval: 10s

scrape_config_files:
  - 'prometheus.private.yml'
scrape_configs:
  - job_name: unpoller
    static_configs:
      - targets: ['unpoller:9130']
  - job_name: ping_exporter
    static_configs:
      - targets: ['ping_exporter:9427']
  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: speedtest_exporter
    scrape_interval: 12h
    scrape_timeout: 1m
    static_configs:
      - targets: ['speedtest-exporter:9798']
  - job_name: waveplus_exporter
    static_configs:
      - targets: ['pibox:9744']
  - job_name: mqtt_exporter
    static_configs:
      - targets: ['mqtt_exporter:9641']
