mqtt:
  server: tcp://mosquitto:1883
  topic_path: zigbee2mqtt/sensor/+
  device_id_regex: "(.*/)?(?P<deviceid>.*)"
metrics:
 - prom_name: temperature
   mqtt_name: temperature
   help: Temperature reading
   type: gauge
 - prom_name: humidity
   mqtt_name: humidity
   mqtt_value_scale: 100
   help: Humidity reading
   type: gauge
 - prom_name: pressure
   mqtt_name: pressure
   help: Pressure reading
   type: gauge
 - prom_name: current
   mqtt_name: current
   help: Current in amps
   type: gauge
 - prom_name: power
   mqtt_name: power
   help: Power in watts
   type: gauge
 - prom_name: power_factor
   mqtt_name: power_factor
   help: Power factor in percent
   type: gauge
 - prom_name: voltage
   mqtt_name: voltage
   help: Voltage in volts
   type: gauge
 - prom_name: ac_frequency
   mqtt_name: ac_frequency
   help: Frequency in Hertz
   type: gauge
